### ISSUE TITLE
pngのテクスチャこわれる

### ISSUE THREAD

**Issue by wistnki** [altseed/Altseed2#144]
#67 #72 
jpeg のテクスチャは読んでちゃんと映るがが png のテクスチャだと壊れる。

![image](https://user-images.githubusercontent.com/12514442/68102347-99214000-ff15-11e9-90e8-c2af957d2172.png)

**Comment by durswd** [comment]
ある程度修正。最終的には、piplinestateでアルファ周りの設定をする必要あり。
