### ISSUE TITLE
Failed test in MacOS 10.15 with build for Linux

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#20]
```shell
$ ./Altseed_Core_Test
[==========] Running 14 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from BaseObject
[ RUN      ] BaseObject.Basic
/Users/wk/altseed/Altseed2-rust/Core/core/test/BaseObject.cpp:10: Failure
Expected equality of these values:
  asd::Core::GetInstance()->GetBaseObjectCount()
    Which is: 2
  0
/Users/wk/altseed/Altseed2-rust/Core/core/test/BaseObject.cpp:13: Failure
Expected equality of these values:
  asd::Core::GetInstance()->GetBaseObjectCount()
    Which is: 3
  1
/Users/wk/altseed/Altseed2-rust/Core/core/test/BaseObject.cpp:22: Failure
Expected equality of these values:
  asd::Core::GetInstance()->GetBaseObjectCount()
    Which is: 2
  0
fish: './Altseed_Core_Test' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by wistnki** [comment]
Windows10でも発生
`
C:\Users\wisteria\Desktop\repos\altseed2\core\test\BaseObject.cpp(10): error: Expected equality of these values:
  asd::Core::GetInstance()->GetBaseObjectCount()
    Which is: 3
  0
C:\Users\wisteria\Desktop\repos\altseed2\core\test\BaseObject.cpp(13): error: Expected equality of these values:
  asd::Core::GetInstance()->GetBaseObjectCount()
    Which is: 4
  1
C:\Users\wisteria\Desktop\repos\altseed2\core\test\BaseObject.cpp(22): error: Expected equality of these values:
  asd::Core::GetInstance()->GetBaseObjectCount()
    Which is: 3
  0
`
