### ISSUE TITLE
同じテクスチャを使ったスプライトを連続して描画できない

### ISSUE THREAD

**Issue by wistnki** [altseed/Altseed2#241]
同じテクスチャを用いる異なるスプライトを連続してDrawSpriteしても、
最初の一つだけしか描画されない。
異なるテクスチャを用いたスプライトのDrawSpriteを挟むと描画できる。

**Comment by wistnki** [comment]
#238 の原因

**Comment by gon6109** [comment]
文字描画も一つの文字列テクスチャから切り出しているため、1文字目しか描画されない
