### ISSUE TITLE
パフォーマンス問題

### ISSUE THREAD

**Issue by wistnki** [altseed/Altseed2#280]
目標FPSを高く設定しても、あまりFPSが上がらない。具体的には
4th Gen Intel Core i7 + iGPU で 30ちょっと
8th Gen Intel Core i7 + RTX2060S で 40ちょっと

どこかしらでおかしなことをしてそうなので、
プロファイラーを載せて調査＆改修が必要

**Comment by wraikny** [comment]
2.9 GHz クアッドコアIntel Core i7
Radeon Pro 560 4 GB
Intel HD Graphics 630 1536 MB

> CoreのReleaseで
> Graphicsの処理あり: 60
> なし: 300
> みたいな感じ

> Input系の呼び出し消したらめちゃくちゃ速くなったが

> `Altseed:Joystick:::GetInstance()->RefreshConnectedState();` これの有無っぽい

> KeyboardとMouseの呼び出しがあってもFPS 4 ~ 5万くらいで、
> さらにGraphicsのBeginFrame EndFrame呼び出しがあっても3000くらい 

> これ本来 RefreshInputState と RefreshBibrateState を呼ぶのでは……？

**Comment by wistnki** [comment]
RefreshConnectedState呼びすぎが大きな要因だったようだけれどどちらにせよプロファイラは必要なのでそのIssueとしておいとく

**Comment by wistnki** [comment]
#87
