### ISSUE TITLE
Joystick のデバイスID

### ISSUE THREAD

**Issue by wistnki** [altseed/Altseed2#370]
https://github.com/altseed/Altseed2/blob/master/core/src/Input/Joystick.cpp#L11-L14
Joystick のデバイスID は複数あるやつがあるのと、純正だけど似たのがいっぱいあるとかあるので、
もう少しうまくやったほうがよさそう。
例えば、DUAKSHOCK4は 1356:1476 もしくは 1356:2508 だし
XBOX のコントローラは純正の飲みに限っても種類がたくさんある。

**Comment by argonism** [comment]
そうなってくると、利用者側でデバイスの種類を指定する形にしたほうが良さそうですね...

**Comment by wistnki** [comment]
それ。もっと上のレイヤー（少なくともEngine）で処理したほうがいい気がする。

**Comment by argonism** [comment]
これなんですが、デバイスの種類を指定してもHIDデバイスの中でどれが指定したデバイスなのか判別できる必要があるので、結局プロダクトIDは必要になっちゃってどうしようという感じですね。
判別に使える情報は下の構造体にある情報だけなので...。
https://github.com/signal11/hidapi/blob/a6a622ffb680c55da0de787ff93b80280498330f/hidapi/hidapi.h#L49
