### ISSUE TITLE
C#: Terminate後に誤ってDoEvents等呼ぶとCoreの例外が吐かれるのをEngine側の例外にする

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#410]

**Comment by wistnki** [comment]
DoEventsに関しては、続行不能という場合falseを返すのがよい。
Updateもかなあ。（DoEvents() == true なら Updateもできるはずで、コケるとしたら違うところが原因なので、こちらは void でいいという話がある）

**Comment by wraikny** [comment]
コード修正中に誤って
```
Engine.Terminate();
Engine.DoEvents();
```
と記述してある状態でRunしてしまってC++側でExceptionが吐かれて少しびっくりしたという話でした。
こういう無効な呼び出しをしたときは InvalidOperationExceptionを返すと良さそうかなとおもいます。

**Comment by wistnki** [comment]
たしかにそれでC++側の例外が出るのは良くなさそう。

**Comment by wistnki** [comment]
Terminateしたあとってログ吐けないよね

**Comment by wistnki** [comment]
ひとまず`Terminate`すると`Core::DoEvents`はちゃんと`false`を返すようにした
