### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#419]
とりあえず未執筆：
- [x] マテリアル
- [x] ポストエフェクト
- [x] ShapeNodes
- [x] パッケージ
- [x] カメラ
- [ ] Pivot / Anchor

**Comment by wistnki** [comment]
- [ ] Pivot

**Comment by wistnki** [comment]
https://github.com/altseed/Altseed2/issues/457

**Comment by wraikny** [comment]
PostEffect https://github.com/altseed/Altseed2-document/pull/29

**Comment by durswd** [comment]
シェーダーと一緒にマテリアルを書く
