### ISSUE TITLE
Core: PostEffect.LightBloomのCoreのtestで見た目がおかしい

### ISSUE THREAD

**Issue by gon6109** [altseed/Altseed2#421]

**Comment by durswd** [comment]
ビルドは通ったが見た目がおかしい？

**Comment by wraikny** [comment]
なお、もともとは
`float4(0.0)` というコードがGLSLでは`vec4(0.0f)`に変換されて正しくコンパイルされていたけどHLSLではこのようなコードは書けないためコンパイルが通っていなかったらしいです（補足・情報共有）
