### ISSUE TITLE
ポストエフェクトのリファクタリング

### ISSUE THREAD

**Issue by wistnki** [altseed/Altseed2#440]

**Comment by wraikny** [comment]
当初`CommandList`等がinternalだった影響で同名メソッドでラップしてあったりして良くないので、直します。すぐ直せるはず。

**Comment by wraikny** [comment]
- [ ] CommandListのメソッドのラッパーメソッドを削除して直接呼び出す。
- [ ] RenderTextureCacheにformatを含める

**Comment by wraikny** [comment]
> RenderTextureCacheにformat
これは別のissueとして立てるのが正しそう
