### ISSUE TITLE
ドキュメント：シェーダリソース番号に関する注意を書く

### ISSUE THREAD

**Issue by wistnki** [altseed/Altseed2#457]
```
Texture2D hogeTex : register(t1);
SamplerState hogeSamp : register(s1);
```
のようなことを頂点シェーダに書いただけだと転送されないのか頂点シェーダで参照できない。
ピクセルシェーダにも書くと参照できるようになる。

**Comment by durswd** [comment]
再現できず

**Comment by wistnki** [comment]
ピクセルシェーダと頂点シェーダで、テクスチャなどのリソースのレジスタ番号は共通なのでその旨の注意を記載する。

例えば：
VS用texture1 PS用texture1,texture2 があったとして
VS用texture1を0番
PS用texture1を0番、texture2 を1番としてシェーダを書くとバグる。
VS用texture1を0番
PS用texture1を1番、texture2 を2番とするなど、とにかく重複しないようにする。
