### ISSUE TITLE
C#: Tranformの伝播の最適化？&&リファクタリング

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#467]
親のTranformNodeの更新があればその全ての子孫のTranformにも更新が行われるはずですが、

この時必ず親から子へ更新していけば、計算は

`parent.AbsoluteTranform * this.Tranform`

だけで良いので、その方が計算コストが小さいと思います。

また、`Size`プロパティには
```
foreach (var descendant in EnumerateDescendants<DrawnNode>())
                {
                    descendant.UpdateSize();
                    descendant.UpdatePosition();
                    descendant.UpdateTransform();
                }
```

という処理がありますが、`Position`と`Scale`には無くてよくわからないので、コード整理したほうが良さそう…………(ごちゃごちゃしている

**Comment by wistnki** [comment]
>parent.AbsoluteTranform * this.Tranform
たしかに

SizeはPivot周りを受けていろいろ書き換えるからでは。
たしかに、ごちゃごちゃしていて、どこかのプロパティをセットすると付随して勝手に変わってしまうようなところもあるので整理したほうがよさそうではある

**Comment by wraikny** [comment]
正直あの辺はスパゲティコードにしか見えない………少なくともコメントは必須のレベル

**Comment by wraikny** [comment]
Transformの伝播って毎フレーム計算してたのか……(Engine.Update)
