### ISSUE TITLE
C#: 先祖ノードを子孫に追加すると循環して無限ループが発生し得る

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#565]
このスレッドに返信しました :
self.AddChildNode(self)できる隙があったのを発見した:ギャー:
これ、thisだけじゃなくて先祖全てまずい（再帰で無限ループになる

**Comment by wraikny** [comment]
- 追加先の先祖に自身があるかどうか、でfilteringする。
- 予約状態も考慮する。

**Comment by wistnki** [comment]
親は一つしか持てないので数珠繋ぎになってるツリーはRootNodeに接続できないからUpdateもされないため、
そういうノードをエンジンが食ったことで無限ループにはまることはなさそう。
