### ISSUE TITLE
C#:is RootNode等のコードがpause中を想定されているか確認する

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#567]
https://github.com/altseed/Altseed2-csharp/blob/d0b9c9b42d9b52ab84670a367b3952c497a1c5ac/Engine/Node/Node.cs#L66

**Comment by wistnki** [comment]
RootNodeもしくはUpdatedNode、でないといけなさそう

**Comment by wraikny** [comment]
`node == Engine.UpdateNode` ？

**Comment by wistnki** [comment]
https://github.com/altseed/Altseed2-csharp/pull/159#issuecomment-671817886
