### ISSUE TITLE
RegisterableCollection.UpdateでのRemoveQueueへの処理の条件が足りない

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#579]
## Describe the bug/概要
削除したノードがそれを持つ`Children (RegisterableCollection class)`の反映がされる前に（= `OnRemoved`内で`RemoveChildNode`を行うことで`Children.Update`が行われないことで、これは容易に発生する）、そのノードを別のノードに追加し、その後元の親ノードを再び追加した後に`Children (RegisterableCollection class)`の更新が走り、 `Error on flushing RemoveQueue!` のメッセージに到達し、削除処理が正常に行われない。

https://github.com/altseed/Altseed2-csharp/blob/master/Engine/Collection/RegisterableCollection.cs

## 詳細
足りない条件:
- 削除予約状態のオブジェクトを同じOwnerに再び追加した場合にcontinueする。
```obj.Status == RegisteredStatus.Registered && obj._Parent == Owner```
- 他のオブジェクトに追加予約状態 または 追加予約受理済みのノードに対しての処理
```
(obj.Status == RegisteredStatus.Registered && obj._Parent != Owner)
|| (obj.Status == RegisteredStatus.WaitingAdded && obj._ParentReserved != Owner && obj._Parent == Owner)
```
AddQueueの条件もバグがありそうな雰囲気を感じる。

## Expected behavior/期待される動作
追加削除が正しく行われる。

## 補足
↑また、上記の処理を眺めた結果、Nodeの更新順によっては追加先で `OnAdded` が呼ばれた後に `OnRemoved` が呼ばれるということが発生するのが非直感的で良くないと思われる。

`OnAdded`/`OnRemoved`を呼び出すのは、実際に`AddChildNode` `RemoveChildNode` された順番で実行されて欲しい。（現状の**仕様**ではNode Treeの更新順に依存する。例えばあるノードの子ノードを削除し、それをそれより先祖のノードの子ノードとして追加した場合、`OnRemoved`が呼び出される前に`OnAdded`が呼び出されてしまう）

実際のコレクションへの追加削除だけ遅延して、`OnAdded`/`OnRemoved`は(`Parent ?? ParentReserved`でRootまで辿れるなら)即座に呼んで良い気もするけど
参考：ナムアニさんの記事
https://qiita.com/NumAniCloud/items/483ed8015b250a68678a

**Comment by wistnki** [comment]
OnAddedは「RootNodeから生える木にぶら下がり、 **次のフレームからUpdateされるよう** になりました」
OnRemovedは「RootNodeから生える木から外れ、 **次のフレームからUpdateされない** ようになりました」
というイベントなので削除即別のNodeにAddした場合はFreeである瞬間がないのでOnRemovedを発火させないようにするのがよさそう。
OnAdded/OnRemoved時呼ぶんなら、RootNodeからぶら下がるかどうかを戻り値で返せば済む話なので。

**Comment by wistnki** [comment]
Add/Removeの条件分岐は直す。

**Comment by wistnki** [comment]
結局、FreeなNodeしかAddできず、RegisteredなNodeしかRemove出来ないように制約を戻した。

また、
* 未登録ノードに対して子孫ノードを登録（待ちに）したあと、そのノードを登録しても、子孫ノードの登録が深さだけ遅延する問題の対応
* 未登録ノードからノードを削除しても、削除処理が行われないので手動で強制執行するメソッドの追加
もやった

https://github.com/altseed/Altseed2-csharp/commit/3e3a6103820cf47293083b0b6c0ce7462ff1dbb6
