### ISSUE TITLE
RenderTexture::Createでエラー

### ISSUE THREAD

**Issue by Funny-Silkie** [altseed/Altseed2#594]
## Describe the bug/概要
C#側でRenderTexture.Createを呼ぶ時，TextureFormatをD24S8，D32，D32S8のいずれかにすると`TextureBase::TextureBase(shared_ptr<LLGI::Texture> texture)` でtextureがnullptrになり死ぬ

## Environment/環境
- OS:
Win10

- Altseed2 version:
2.0.0-beta2

## To Reproduce/再現手順
C#側でRenderTexture.Createを呼ぶ時，TextureFormatをD24S8，D32，D32S8のいずれかにする

## Expected behavior/期待される動作
TextureBase.cppの95行目でメモリアクセスエラー

**Comment by durswd** [comment]
https://github.com/altseed/Altseed2/pull/603
