### ISSUE TITLE
GenerateFontFileで出力先のディレクトリが存在するか確認する。

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#614]
## Describe the bug/概要

```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Altseed2.Font.cbg_Font_GenerateFontFile(String dynamicFontPath, String staticFontPath, Int32 size, String characters)
   at Altseed2.Font.GenerateFontFile(String dynamicFontPath, String staticFontPath, Int32 size, String characters)
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
エラーのため停止しました
```
が発生する

## Environment/環境
- OS: Wndows 10

- Graphics: 

- Altseed2 version: https://github.com/altseed/altseed2/tree/088a0b030f796f659d2fa15f0a4b280cba02f51a

## To Reproduce/再現手順
1. 出力先に存在しないディレクトリ以下のパスを指定する

## Expected behavior/期待される動作
Logを出してfalseを返す。

**Comment by wraikny** [comment]
ふぁいるはこれ
https://github.com/altseed/Altseed2/blob/master/core/src/Graphics/Font.cpp

**Comment by wraikny** [comment]
```
auto staticFontDir = /* staticFontPath の親ディレクトリを取得する */
if (!FileSystem::GetIsDirectory(staticFontPath))
{
    // logを吐く
    return false;
}
```

**Comment by wraikny** [comment]
ついでに
```
RETURN_IF_NULL(dynamicFontPath, false);
RETURN_IF_NULL(staticFontPath, false);
RETURN_IF_NULL(characters, false);
```
をそれより前に追加して欲しい。

**Comment by TsubaMukku** [comment]
一つ確認ですが、
これの作業環境って、OS: Wndows 10を想定してます？？
私、MacでOS: Mojave10.14.6なのですが大丈夫でしょうか？
（ほんとに、こういうの初めてなので、こういうこともわからないです。一応確認させていただきました）

**Comment by TsubaMukku** [comment]
一つ確認ですが、
これの作業環境って、OS: Wndows 10を想定してます？？
私、MacでOS: Mojave10.14.6なのですが大丈夫でしょうか？
（ほんとに、こういうの初めてなので、こういうこともわからないです。一応確認させていただきました）

**Comment by TsubaMukku** [comment]
一つ確認ですが、
これの作業環境って、OS: Wndows 10を想定してます？？
私、MacでOS: Mojave10.14.6なのですが大丈夫でしょうか？
（ほんとに、こういうの初めてなので、こういうこともわからないです。一応確認させていただきました）

**Comment by TsubaMukku** [comment]
一つ確認ですが、
これの作業環境って、OS: Wndows 10を想定してます？？
私、MacでOS: Mojave10.14.6なのですが大丈夫でしょうか？
（ほんとに、こういうの初めてなので、こういうこともわからないです。一応確認させていただきました）
