### ISSUE TITLE
Macでlibclangを通すとshared_ptr<T>がすべてint &となってしまう。

### ISSUE THREAD

**Issue by wraikny** [altseed/Altseed2#668]
## Describe the bug/概要
`generate_cbg_definition.py` をmacで実行すると、タイトルどおりに。

## Environment/環境
- OS: macOS Catalina 10.15.4
- Python: 3.8.6
- LLVM: 11.0.0 (`/usr/local/Cellarlvm/11.0.0/lib`)

## To Reproduce/再現手順
1. homebrewでllvmインストール
1. pipでlibclangインストール 
1. `python scripts/generate_cbg_definition.py '/usr/local/Cellar/llvm/11.0.0/lib'` などと実行
1. `scripts/bindings/auto_generate_define.py` を見る
1. 
<img width="1094" alt="スクリーンショット 2021-02-01 13 23 26" src="https://user-images.githubusercontent.com/29581531/106415048-7d4a7800-6491-11eb-8a59-9a59517a007c.png">

また、 `test-libclang`ブランチにlibclang単体での動作確認ようのコードを追加した
https://github.com/altseed/Altseed2/tree/test-libclang

https://github.com/altseed/Altseed2/blob/test-libclang/scripts/test_libclang.py

## Expected behavior/期待される動作
shared_ptr<T>はshared_ptr<T>のまま得られてほしい。

**Comment by wraikny** [comment]
wraikny/れいにー  14:26
shared_ptrはint&になりますか？

swd  14:29
存在すらしない
14:29
@GON @wraikny/れいにー おそらくllvm11が原因な気がしてて、生成されたメソッドから引数が抜け落ちてたりします
:天使の笑顔:
2


GON  14:32
#include <memory>
とかがちゃんとできてないとかですかね...?
環境によってインクルードディレクトリが異なってる説
:天使の笑顔:
1


swd  14:35
テスト書こう！
14:35
環境ごとに違いすぎ

**Comment by durswd** [comment]
多分直した
