### ISSUE TITLE
DrawnExtension.UpdateIsDrawnActuallyOfDescendants

### ISSUE THREAD

**Issue by wistnki** [altseed/Altseed2#680]
別種の ICullableDrawn な Node による親子をうまく扱えない気がするので要調査

**Comment by wraikny** [comment]
Altseed2で、SpriteNodeにTextNodeをAddChildNodeした場合、
SpriteNode（親）のIsDrawnがTextNode（子）にIsDrawnActuallyとして引き継がれないけど
これはバグですかね？
（https://github.com/altseed/Altseed2/issues/680たぶんこれ？）

IDrawn.csのDrawnExtension.UpdateIsDrawnActuallyOfDescendants

if (child is T)

を IDrawn
