### ISSUE TITLE
altseed.github.ioのリファレンスが開けない

### ISSUE THREAD

**Issue by UweSilver** [altseed/Altseed2#691]
## Describe the bug/概要
上のタブからリファレンスのトップに行こうとすると、404になるか、リンクを踏めない。
/References/index.htmlがないといわれます。

また、機能解説の頁に貼られているリファレンスへのリンクだと思われるものも機能していないようです。

**Comment by wraikny** [comment]
報告ありがとうございます。
CIによる自動更新にした影響だと思われます、調査します。

**Comment by UweSilver** [comment]
きちんと機能しているようです
ありがとうございます
